### ISSUE TITLE
Repeater Fields causes errors on Gravity Form

### ISSUE THREAD

**Issue by onlyskyguy** [kodie/gravityforms-repeater#1]
Whenever I add a repeater field into a form, the form starts getting "messed up"... and the repeater buttons don't even work (tried in both preview mode and on the rendered form).

For example, the progress bar starts showing up on my multipage form, when I set it back to "steps" and save the form, it switches back to progress bar and doesn't save changes to the form. There are a couple other small quirks too but overall the repeater plugin basically breaks my form. When I disable the repeater plugin, things go back to normal.

There are no javascript errors showing up either. Have you seen this kind of behavior before? Would really like to get the repeater field working and it looks like a great plugin other than this. Thanks for your help!

**Comment by kodie** [comment]
Hey there Orestis! Thank you for trying out my plugin and I apologize for it causing you some issues.

First, can you verify that you don't have your form's ajax enabled? Currently this plugin doesn't support ajax enabled forms. (I'm hoping to fix that in the near future).

On my test form I made a multi-page form with a repeater on the second page and switched the Progress Indicator back and forth and notice that it didn't seem like it was saving the changes (it would just go back to 'Progress Bar' on the form editor) but when I went back and looked at the form on the front-end, the changes were actually saved! That's a weird bug so I'll have to do some digging and find out why my plugin would be causing that.

**Comment by onlyskyguy** [comment]
Ok I'll try that out right now. Having a repeater field is awesome so I
appreciate the work you've done with this!

On Mon, Nov 23, 2015 at 11:21 AM, Kodie Grantham notifications@github.com
wrote:

> Hey there Orestis! Thank you for trying out my plugin and I apologize for
> it causing you some issues.
> 
> First, can you verify that you don't have your form's ajax enabled?
> Currently this plugin doesn't support ajax enabled forms. (I'm hoping to
> fix that in the near future).
> 
> On my test form I made a multi-page form with a repeater on the second
> page and switched the Progress Indicator back and forth and notice that it
> didn't seem like it was saving the changes (it would just go back to
> 'Progress Bar' on the form editor) but when I went back and looked at the
> form on the front-end, the changes were actually saved! That's a weird bug
> so I'll have to do some digging and find out why my plugin would be causing
> that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kodie/gravityforms-repeater/issues/1#issuecomment-159035297
> .

## 

Orestis Herodotou
Lead UX Developer, Only Sky http://www.onlysky.com/
orestis@onlysky.com
415-294-0387

http://www.onlysky.com/

**Comment by kodie** [comment]
No problem Orestis! Let me know if switching off ajax fixes that for you!

**Comment by onlyskyguy** [comment]
Switching off ajax makes the forms work, but it's still resetting the
progress bar, which is extremely annoying :( as we have to re-enter each
page title every time we save.

Hopefully this can be resolved soon, thanks again for your help!

On Mon, Nov 23, 2015 at 1:49 PM, Kodie Grantham notifications@github.com
wrote:

> No problem Orestis! Let me know if switching off ajax fixes that for you!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kodie/gravityforms-repeater/issues/1#issuecomment-159076394
> .

## 

Orestis Herodotou
Lead UX Developer, Only Sky http://www.onlysky.com/
orestis@onlysky.com
415-294-0387

http://www.onlysky.com/

**Comment by kodie** [comment]
I will try to get this fixed for the next release coming up. Thank you.

**Comment by onlyskyguy** [comment]
You are awesome let me know if there's anything I can help with.

**Comment by kodie** [comment]
This bug was fixed in the 33ef391 commit.
