### ISSUE TITLE
Pre-populating checkboxes

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#11]
Hi Kodie, 

Could you please test or document how pre-populating checkboxes should work? 

I can't figure out how to get them to pre-populate. 

If it matters, I'm trying to get them to pre-populate on pages 1 and 2 of a multi-page form (two repeaters, one on page on, one on page 2, each with a checkbox field). 

Thanks,
Michael Moore

**Comment by kodie** [comment]
Hey Michael! I will look into this today and get back to you!

**Comment by kodie** [comment]
@stuporglue I fixed this in the f9f9203 commit. Test it out using the latest development version of the plugin.

Populate multiple checkboxes by passing it comma separated values.

See how to get the development version of the plugin here:
https://github.com/kodie/gravityforms-repeater#development
