### ISSUE TITLE
warning text appears on submission

### ISSUE THREAD

**Issue by reggiescottjr** [kodie/gravityforms-repeater#13]
Everytime I submit a form I get an error message that displays on the confirmation page. The form goes through but displays this code at the top:

 Warning: substr() expects parameter 1 to be string, array given in /home3/sjgas/public_html/contractorsonly/wp-content/plugins/repeater-add-on-for-gravity-forms/class-gf-field-repeater.php on line 143

Can you lend any insight as to why this is happening?

**Comment by kodie** [comment]
Hey @reggiescottjr! Thanks for bringing this to my attention. I will look into it and get back to you within the next day or so.

**Comment by kodie** [comment]
I fixed this in the 94b7076 commit and is now on the latest development version.

Test it out by installing the latest development version or you can wait until the stable version is released. (Hopefully soon)

Find out how to get the latest development version here: https://github.com/kodie/gravityforms-repeater#development

**Comment by reggiescottjr** [comment]
Thanks man!
