### ISSUE TITLE
Do I need an extra library for jQuery().mask?

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#14]
I'm getting errors "jQuery(...).mask is not a function" on gf-repeater.js, line 254. 

Do I need to install an extra jQuery library for that to work or is it likely that I've broken something else locally? I'm using gravityforms-repeater Version 1.0.8.

**Comment by kodie** [comment]
hmmm, that's a weird one. Gravity Form's input mask file should be enqueued automatically if one of your fields use an input mask. What kind of field are you having the issue with?

**Comment by stuporglue** [comment]
I've got phone numbers and email fields, but only inside the repeater. 

I just discovered that if I add a field with a mask outside of the repeater, then jquery.maskedinput.min.js is enqueued, but if all of my masked fields are inside the repeater, that .js file is not enqueued, which results in the error above.

**Comment by kodie** [comment]
ok, I think I may have an idea of what the issue is. I'll get back to you later today.

Thanks!

**Comment by kodie** [comment]
Is there anything special about your form? Multi-page, additional plugins, custom fields, multiple forms on the same page, multiple repeaters on the same form/page?

**Comment by stuporglue** [comment]
The form is a multi-page form. There's only one form on the page and only one repeater in the form. 

Several GF add-ons: Authorize.net, MailChimp, Stripe. 

I'm deactivating them all now to see if that helps.

**Comment by stuporglue** [comment]
I disabled all GF related plugins except GF itself and your plugin and am still having the same issue. 

I also deleted the form's page-break so it's now a single page form.

I've attached my form definition json file here in case it sheds any light on the issue. 

[mask_function_not_found.txt](https://github.com/kodie/gravityforms-repeater/files/75222/mask_function_not_found.txt)

**Comment by stuporglue** [comment]
I figured it out. 

It turns out that this form was created initially with a tool that generates a JSON file which is imported into GF. 

It looks like that tool didn't set dateFormat or dateType for the date field or phoneFormat for the phone field which is part of what GF uses to determine if it should 

After setting the formats, jquery.maskedinput.min.js loaded.

Sorry for the bad bug report

**Comment by kodie** [comment]
Good to hear! :beers:
