### ISSUE TITLE
JS error when you have a required date field with a calendar icon

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#15]
I'm getting error messages in gf-repeater.js on line 290

```
 if (childRequired) {
    var splitName = newInputName.replace('.', '_').split(/(_|-)/);
```

newInputName is undefined. 

It looks like this is only happening when you have a required date field which has an icon (calendar or custom) set. It seems that the icon image URL is put in a hidden field which has no name property. 

This results in inputId having a value, but inputName being undefined on lines 227/228, then since the date field is required, gf-repeater.js tries to split the undefined newInputName. 

It seems that that this only causes an actual problem sometimes. One of my forms won't advance to the next page because of the error, but another one of my forms will. Both are multi-page and neither are using ajax. The error shows up in the console in both cases. I haven't figured out what's different between the two forms. For the time being I just edited gf-repeater.js to check if(newInputName && childRequired).

**Comment by kodie** [comment]
Thanks for letting me know Michael! I'll have a patch released for this soon.

**Comment by kodie** [comment]
I believe I fixed this in the latest development version. Try it out and let me know! Thanks!

Find out how to get the latest development version here: https://github.com/kodie/gravityforms-repeater#development
