### ISSUE TITLE
Conditional field has to be inside of repeater

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#16]
I have a section inside of the repeater which I only want to show if a field, which is outside of the repeater has a certain value.

It seems that the conditional logic checks only allow me to pick fields inside the repeater, otherwise the form fails to render with the message: "child is undefined".

**Comment by kodie** [comment]
Thanks for the suggestion! I will see about getting this implemented in the next release.

**Comment by kodie** [comment]
Hey @stuporglue! I fixed this in the latest development version. Fields inside of the repeater now respect conditional logic from outside the repeater. 🍺

**Comment by stuporglue** [comment]
Thanks Kodie, this is fantastic!
