### ISSUE TITLE
Conditional sections don't hide fields inside section

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#17]
The GF way of doing sections is kind of weird, since there's no actual nesting, but all fields after a section are considered to be part of the section until the next section or page starts. 

Outside of repeaters, conditionally hiding a section will hide all fields inside that section. 

Inside a repeater just the section header itself seems to be hidden, the subsequent fields are still shown.

**Comment by kodie** [comment]
Another good suggestion! I will try to get this implemented in the next release.

**Comment by kodie** [comment]
@stuporglue I fixed this in the latest development version but unfortunately there seems to be a slight side-effect that I may have to look into fixing in the future: When hiding a section with conditional logic inside of a repeater, it now hides all fields under the section, BUT, it also hides all fields under the section outside of the repeater which also includes the repeater end field (where the + and - buttons are).

I'm going to see what I can do to contain the section's conditional logic inside of the repeater but that may have to wait for a little bit.

Thanks for the suggestion!

**Comment by jaysonbrown** [comment]
I really need this too!

**Comment by WebImage** [comment]
+1.  Just ran into this issue as well.

**Comment by kodie** [comment]
Just added this in the latest development version!
