### ISSUE TITLE
Errors after update

### ISSUE THREAD

**Issue by zitrusblau** [kodie/gravityforms-repeater#18]
Hi Kodie,

after update your plugin I get the following errors:

Notice: Undefined offset: 0 in /Applications/MAMP/htdocs/grell_neu/wp-content/plugins/repeater-add-on-for-gravity-forms/class-gf-field-repeater.php on line 512

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/grell_neu/wp-content/plugins/repeater-add-on-for-gravity-forms/class-gf-field-repeater.php on line 556

I'll get these errors on a form which is **not** using your repeater plugin! On the form which is using your plugin are no errors.

**Comment by kodie** [comment]
Hey @zitrusblau! I'm pretty sure I have an idea about what is causing this error. I will get it fixed and try to get a patch released for it soon! Thanks!

**Comment by kodie** [comment]
I'm pretty sure I fixed this in the latest development version. Please try it out and let me know if that fixed it. Thanks!

Find out how to get the latest development version here: https://github.com/kodie/gravityforms-repeater#development

**Comment by zitrusblau** [comment]
Hi @kodie,

I try ist out and the first error is fixed but the second still remains:
Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/grell_neu/wp-content/plugins/gravityforms-repeater-development/class-gf-field-repeater.php on line 556

**Comment by kodie** [comment]
@zitrusblau Can you tell me which version of the repeater plugin you were using before you upgraded?

**Comment by zitrusblau** [comment]
@kodie it was the latest stable version 1.0.8

**Comment by kodie** [comment]
And which version did you upgrade to 1.0.8 from?

**Comment by zitrusblau** [comment]
Version 1.0.7.2

**Comment by kodie** [comment]
Can you open up class-gf-field-repeater.php and looking at the "gform_disable_ajax" function and check if $args is being passed to the function and also see if $form is being found.

So maybe replace the whole function with this:

```
    public static function gform_disable_ajax($args) {
        print_r($args);
        $get_form = GFFormsModel::get_form_meta_by_id($args['form_id']);
        $form = reset($get_form);
        print_r($form);

        if (GF_Field_Repeater::get_field_index($form) !== false) {
            $args['ajax'] = false;
        }

        return $args;
    }
```

and tell me if either hose those output anything.

Thanks!

**Comment by zitrusblau** [comment]
Attached I send you two screenshots. The first is the result on a form which have the repeater field, the second is the result on a form without repeater field but with error.
![gf_repeater1](https://cloud.githubusercontent.com/assets/6340749/12257755/606c087c-b909-11e5-89a6-f2fb879982aa.png)
![gf_repeater2](https://cloud.githubusercontent.com/assets/6340749/12257754/60685e02-b909-11e5-94f4-1f541bd37db0.png)

**Comment by kodie** [comment]
@zitrusblau This helps me a lot! I released another development version that hopefully fixes that for you. Let me know! Thank you!

**Comment by zitrusblau** [comment]
@kodie The warning about the foreach is fixed, but now I get the following warning:
Warning: array_key_exists() expects parameter 2 to be array, boolean given in /Applications/MAMP/htdocs/grell_neu/wp-content/plugins/gravityforms-repeater-development/class-gf-field-repeater.php on line 556

Also only on the form without the repeater field!

**Comment by kodie** [comment]
@zitrusblau Sorry about that, I released another development version. Try that and let me know if it works.

**Comment by zitrusblau** [comment]
@kodie All fixed now, thank you!

**Comment by kodie** [comment]
Awesome! Thanks for all the help!
