### ISSUE TITLE
Feature Request: remove arbitrary repeated section

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#19]
It'd be nice to be able to remove any arbitrary repeated section, not just the last section.

**Comment by kodie** [comment]
@stuporglue Are you meaning like with the Javascript functions?

The `gfRepeater_unrepeatRepeater` function supports specifying a childId.

`gfRepeater_unrepeatRepeater(formId, repeaterId, repeaterChildId);`

**Comment by stuporglue** [comment]
I was thinking of the +/- buttons that show up at the bottom of the
repeater. It'd be nice to have a (-) button below each item.

I suppose with the js functions I could use an html field and the
[gfRepeater-count] shortcode to display a (-) button and remove the right
child.

**Comment by kodie** [comment]
Oh! I see! That's a good idea! I will see about implementing this in the next release! Thanks!

**Comment by kodie** [comment]
The [gfRepeater-buttons], [gfRepeater-add], and [gfRepeater-remove] shortcodes were just added in the 6279ac4 commit!

Check it out by installed the latest development version!

**Comment by stuporglue** [comment]
Thanks Kodie!
