### ISSUE TITLE
Feature Request: A way to distinguish which input a value came from in multi-input fields

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#20]
I've got some name and address fields in a repeater. if a user doesn't fill out one of the optional name or address parts (eg. Name Suffix, or Address Line 2) then those empty values don't get included in the serialized string that's stored with the form.

When trying to de-serialize these values to pre-populate or otherwise use the values, this results in ambiguity about which input a value corresponds to. 

It would be convenient if the serialized string preserved the input name somehow. 

See the attached screenshot for a visual explanation.

Eg. 
![seriialized_values](https://cloud.githubusercontent.com/assets/16576/12460276/a3fdd546-bf78-11e5-86a1-db9605537a3d.png)

**Comment by kodie** [comment]
So if I understand correctly, if the non-required field is left blank, you'd like it to show a blank value in the entry rather than not display anything at all? Correct?

**Comment by stuporglue** [comment]
Showing a blank value would be one option and would work fine. 

The other option would be to use an associative array instead of a numeric array, where the keys of the associative array were the keys of the field the values came from. 

The 2nd option would be more consistent with how non-repeater fields are presented, but either option would be useful.

**Comment by kodie** [comment]
Ok, I think I understand. This may be something I look into for the next major release. I'm planning on doing a big overhaul and changing the way a lot of things work.

**Comment by kodie** [comment]
ok! in the latest development version I have made it where instead of the array keys starting at 0 and increasing every field that isn't blank, it now uses 0 if there was only one input and the dot notation for the key otherwise.

So in your example, your array would now look like this:

``` php
$unserialized[1][8][1] = '932 Sessame St.';
$unserialized[1][8][3] = 'Blaine';
$unserialized[1][8][4] = 'Alaska';
$unserialized[1][8][5] = '55432';
$unserialized[1][8][6] = 'United States';
```

Let me know if that works for you!

**Comment by stuporglue** [comment]
While I haven't tested it yet, that looks like it'll work out wonderfully.

Thank you!

## 

Michael
