### ISSUE TITLE
Regression between 1.0.8 and 1.0.9 on multi-page forms

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#21]
Hi!

I've got a multi-page form with a repeater on page 1. 

When I submit my form using plugin version 1.0.8 the data saves correctly, but in version 1.0.9 I get empty values. Interestingly, it does show the correct number of empty values, just not the values themselves. 

The form I'm testing this on is extremely simple. Page one is just a repeater with a single text field in it. Page two has a text field and a radio button. 

![submitted_with_version_1 0 8](https://cloud.githubusercontent.com/assets/16576/12689824/d6415a7c-c6a4-11e5-9a94-5c0c24b01425.png)
![submitted_with_version_1 0 9](https://cloud.githubusercontent.com/assets/16576/12689825/d6466e54-c6a4-11e5-9664-4352e8aa3627.png)

Thanks!

**Comment by kodie** [comment]
I'm looking into this issue and should have a fix made soon.

**Comment by kodie** [comment]
Fixed in the 1535efa commit on the latest development build
