### ISSUE TITLE
Feature Request: JS trigger that fires after repeater loading/initialization is complete

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#23]
Hi Kodie, 

It would be convenient if there were a JS trigger that we could listen for to detect when the repeater is done loading. 

This would allow users to run custom JavaScript functions that need to interact with the repeater in some way.

**Comment by kodie** [comment]
Hey Michael! I implemented this feature in the 1.0.9 release! Check for the trigger 'gform_repeater_init_done' on the form to check when a specific form is done loading all of it's repeaters or check that same trigger on the window to check if all the repeaters on the page are done loading.

**Comment by stuporglue** [comment]
Thanks! 

Sorry I didn't see that. I'm still on 1.0.8 because I've got a multi-page form and was hitting #21
