### ISSUE TITLE
Invalid argument supplied for foreach in class-gf-field-repeater.php

### ISSUE THREAD

**Issue by WebImage** [kodie/gravityforms-repeater#24]
The following PHP error is shown when viewing an entry's details in admin if no child fields within the repeater have been filled out.

Warning: Invalid argument supplied for foreach() in repeater-add-on-for-gravity-forms\class-gf-field-repeater.php on line 384.

**Comment by ryansigg** [comment]
Getting this one too.
Thanks for the fix @WebImage

**Comment by kodie** [comment]
Thanks to @WebImage a fix was made in the latest development version of the plugin.

Find out how to get the latest development version here: https://github.com/kodie/gravityforms-repeater#development
