### ISSUE TITLE
tabindex="NaN" when gform_tabindex is false

### ISSUE THREAD

**Issue by rianrietveld** [kodie/gravityforms-repeater#28]
Hi Kodie,
Thank you for this outstanding plugin, very useful!

I found the following issue:
For every GF I add `add_filter( 'gform_tabindex', '__return_false' );` to disable the tab-indexes.

I noticed that this displays in the HTML as `tabindex="NaN"`

For example in 
`<select name="input_4-1-1" id="input_2_4-1-1" onchange="gf_apply_rules(2,[9,10]);" class="medium gfield_select" data-repeater-inputid="1" tabindex="NaN">`

Best would to remove the tabindex attribute completely when gform_tabindex is false.

Kind regards,
RIan Rietveld

**Comment by kodie** [comment]
Hey Rian! Thanks for letting me know about this issue! I just fixed it in the latest development version of the plugin.

See how to get the development version of the plugin here:
https://github.com/kodie/gravityforms-repeater#development

**Comment by rianrietveld** [comment]
Thank you! +1 :-)
