### ISSUE TITLE
Date popup calendar doesn't popup within repeater

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#3]
If I have a date field inside a repeater the JS calendar doesn't pop up.

The calendar popup on the date field outside of the repeater does work.

**Comment by kodie** [comment]
Thanks for bringing this to my attention Michael! I will try to have this fixed in the next release.

**Comment by stuporglue** [comment]
This is probably the same issue as the bug over on wordpress.org:  https://wordpress.org/support/topic/conflict-with-enable-enhanced-user-interface

**Comment by kodie** [comment]
This bug was just fixed in the f6a24a3 commit and will be in the next release.
