### ISSUE TITLE
Conditional Open/Close Blocks

### ISSUE THREAD

**Issue by jproffitt3ge** [kodie/gravityforms-repeater#32]
If would be useful if the opening and closing blocks themselves could be shown/hidden conditionally, in instances where you don't want to allow people to add any items.

**Comment by kodie** [comment]
Hey @jproffitt3ge this feature was actually added in the latest development version which I'm working on getting ready for release. If you don't feel like waiting you can get the development version here: https://github.com/kodie/gravityforms-repeater#development
