### ISSUE TITLE
How can I pre-populate some repeater entries? 

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#4]
Is there a built-in way to pre-populate the repeater with some data? 

It's working really well for submitting data on the site I'm building, now I'd like to add the ability for users to edit entries they've made previously. 

I'd prefer to do it server-side, but it looks like if there's no baked-in method, then I could pass my values to the client with wp_localize_script, then use gfRepeater_setRepeater and populate the values manually with JavaScript....but, if there's a shortcut that'd be nice.

**Comment by kodie** [comment]
Hey Michael! This is a good idea! I'll put it on my to do list! Thank you!

**Comment by kodie** [comment]
Hey Michael! I thank you for your contribution as it gave me some ideas. Support for pre-populating repeated fields was added in the f2ce722 commit and will be in the next release. You are able to pre-populate fields using the normal built in Gravity Forms filters and hooks. I'll have more documentation on this in the readme soon but pretty much you set the parameter name in the form editor like usual and then you can set the parameter either by URL:

http://mywebsite.com/pagewithform?parameter_name=value%20here
^ this would set the value of the field every time it's repeated OR you can do this:

http://mywebsite.com/pagewithform?parameter_name3=value%20here
^ this would set the value of the field only on the 3rd time it's repeated.

You can also use the gform_field_value_ filter in that way as well.

I also just added support to override the repeater 'start' setting with the parameter using the normal methods in the b943a14 commit,

Thanks again!
