### ISSUE TITLE
Undefined index: conditionalLogic

### ISSUE THREAD

**Issue by roryashfordbentley** [kodie/gravityforms-repeater#51]
Small issue that is throwing a notice. 

I have disabled ajax on the form as instructed and I have noticed that if I add custom Add and remove markup to the 'Repeater End' it throws a bunch of 'Undefined Index: conditionalLogic' notices when I click the Add button.

the html I have added to each is 
`<button class="btn btn--tiny btn--primary">Add Another Timesheet</button>` 
and 
`<button class="btn btn--tiny btn--secondary">Remove Timesheet</button>`.

Without custom code in there it works without error.

**Comment by skillmatic-co** [comment]
It may have to an `<a>` tag.

**Comment by roryashfordbentley** [comment]
I'll test it tomorrow and report back. Thanks @tenold.

**Comment by roryashfordbentley** [comment]
Works perfectly with `<a>`
