### ISSUE TITLE
Show as many repeated instances as there is pre-populated data

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#7]
Right now even if I pass pre-populate data for a repeater to be repeated multiple times it only repeats once. 

Eg. if I have input1=asdf&input2=qwer&input3=zxcv

When I click the plus button to add additional repeater sections the pre-populated data shows up in the new sections. 

One of the most common use cases for pre-populating data is probably for users to re-edit data they've entered previously. In such a case, the user will expect to see the data they entered initially. If I pass in pre-populate data, I think it should show up on the screen.

**Comment by kodie** [comment]
Hey Michael! Thank you for the suggestion! I will see about implementing that in the next release! For now you can actually set a prepopulate parameter on the repeater start field itself and set that for example:

input1=asdf&input2=qwer&input3=zxcv&repeater=3

**Comment by kodie** [comment]
Good news Michael! I have implemented this in the d956dd7 commit and it will be in the 1.0.7 release coming in the next day or so! Thanks again for your suggestion! :beer:
