### ISSUE TITLE
Multi Page forms seem to be broken

### ISSUE THREAD

**Issue by kLOsk** [kodie/gravityforms-repeater#8]
Hi,
I have a large multi page form. It seems the the repeater addon breaks the multi page functionality (can't navigate to the previous/next page via buttons. Have to hit enter in a field to switch to the next page). I also get some javascript error from the plugin in jquery.postcaputer.min.js:

'''
Uncaught TypeError: Cannot read property 'length' of undefined
'''

Would be great if you knew how to fix it....

**Comment by kodie** [comment]
Hey Daniel! I'm aware of the issue and am working on a patch now. Stay tuned!

**Comment by kLOsk** [comment]
Awesome thanks :)

**Comment by kodie** [comment]
The 1.0.7.1 update has been pushed out!
