### ISSUE TITLE
Searching for 1.1.0-dev14 - Updated Version

### ISSUE THREAD

**Issue by tonymwaruka** [kodie/gravityforms-repeater#89]
Version 1.0.9 has known bugs and we're trying to get a hold of the dev version 1.1.0-dev14. Anyone?

**Comment by lukecav** [comment]
Yep the version in the master branch.

https://github.com/kodie/gravityforms-repeater/blob/master/repeater.php

Version: 1.1.0-dev14

https://github.com/kodie/gravityforms-repeater/archive/master.zip

**Comment by garretthyder** [comment]
As @lukecav indicated use master. And note you can use Github Updater to handle updating to that version.
See my comment here - https://github.com/kodie/gravityforms-repeater/issues/66

**Comment by tonymwaruka** [comment]
You guys rock, thank you thank you.
