### ISSUE TITLE
Get values of repeater using PHP?

### ISSUE THREAD

**Issue by fakeartist** [kodie/gravityforms-repeater#91]
Hi. I use the 

    $value = GFAPI::get_entry($entry_id);

to get the details from a form entry.

But when I echo the ID of the repeater holder

    echo $value['repeater-id'];

 it return a string like this:

    a:1:{i:1;a:7:{i:161;a:1:{i:1;s:9:"test";}i:162;a:1:{i:1;s:9:"test";}i:163;a:1:{i:1;s:9:"test";}i:164;a:0:{}i:165;a:0:{}i:166;a:0:{}i:167;a:1:{i:1;s:9:"test";}}}

Any PHP function with which I could get these values as a PHP array?

**Comment by stuporglue** [comment]
That's a standard PHP serialized object (an array, in this case). You can use http://php.net/manual/en/function.unserialize.php to turn it into a regular array and work with it.

**Comment by fakeartist** [comment]
Thanks a lot! Works like a charm!
