### ISSUE TITLE
Question About the List Field Type

### ISSUE THREAD

**Issue by leepeterson** [kodie/gravityforms-repeater#97]
Curious how this add-on, Gravity Forms Repeater, differs from the built-in List field type. Obviously you've created a way to group fields and make those groups repeatable as opposed to creating repeatable text inputs (or date, dropdown, etc. via 3rd-party add-ons). But I'm just wondering if this add-on set out to accomplish something that wasn't already available in GF and if it's still providing something not natively available.

Also, is there a roadmap for enhancements so that I can begin contributing?

**Comment by garretthyder** [comment]
Hi @leepeterson the GF list field only supports text entry, whereas this plugin allows you to repeat any field including conditional functionality.
You can see an example I built with it here - http://biologica.ca/request-a-quote/
And I'm sure @kodie would love your contributions he made a post about it here;
https://github.com/kodie/gravityforms-repeater/issues/75
* I don't believe there's an official roadmap as he's not actively developing but is happy to accept contributions.
Cheers

**Comment by leepeterson** [comment]
Whoa! That's a slick form!! I've got a few add-ons which allow for other field types within the List field type, and I knew how this differed from a high level, but now I see that there's a substantial difference. It's not only what's allowed within a repeatable element, it's the markup, the AJAX-enabled generation of new field groups, etc. This is quite impressive.

Thanks for following up and sending an example. Loving it.

**Comment by garretthyder** [comment]
No worries @leepeterson glad I could help and that you like the form/plugin. All the best
